### ISSUE TITLE
Remonté "Total autonomy rate" toutes les 3 à 12 heures

### ISSUE THREAD

**Issue by enamaryn** [acesyde/hassio_mylight_integration#116]
### System Health details

-----
## System Information

version | core-2024.5.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.29-haos
arch | aarch64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4999
Installed Version | 1.34.0
Stage | running
Available Repositories | 1391
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 38.7 GB
disk_used | 6.9 GB
healthy | true
supported | true
board | generic-aarch64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.2.0), File editor (5.8.0), Frigate (0.13.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 0
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 18 mai 2024 à 07:47
-- | --
current_recorder_run | 24 mai 2024 à 16:05
estimated_db_size | 132.23 MiB
database_engine | sqlite
database_version | 3.44.2

</details>
------------

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/acesyde/hassio_mylight_integration/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Bonjour, 

J'ai installé la dernière version de l'intégration MyLight 1.1.0, malheureusement j'ai des mauvaises remontés du "total autonomy rate". Les intervalles sont entre 3 et 12h pour l'update, quand les autres entités se font toutes les 5 minutes. J'aurais aimé l'utilisé sur mon tableau de bord principal pour aidé à la décision notamment, lancer lave vaisselle, lave linge.. etc Mais il reste bloqué sur 54.5% d'autonomie électrique depuis que j'ai installé l'intégration.

### Reproduction steps

1. Installer l'intégration
2. Ajouter une carte "jauge"
3. Voir les updates..
...

### Debug logs

```text
en cours
```

### Diagnostics dump

pas compris

**Comment by acesyde** [comment]
Hello @enamaryn,

Je suis étonné, car la métrique est récupérée toutes les 15 minutes (comme toutes les métriques)

![image](https://github.com/acesyde/hassio_mylight_integration/assets/958435/a49deb19-611e-45a3-ac98-876ef9e78af3)

As tu regarder sur le portail de mylight si cette valeur évolue ?

**Comment by enamaryn** [comment]
@acesyde merci de ton retour rapide ! Je regarde sur l'app et sur le site web, cette donnée est à 100% en ce moment même. Batterie avec du stock et je produis assez pour couvrir ma consommation actuellement.

<img width="1137" alt="Capture d’écran 2024-05-25 à 18 43 23" src="https://github.com/acesyde/hassio_mylight_integration/assets/40593656/9a482722-f5cc-4406-b184-5aa1b5625aaf">
<img width="590" alt="Capture d’écran 2024-05-25 à 18 45 24" src="https://github.com/acesyde/hassio_mylight_integration/assets/40593656/b20d4a3d-de6b-4669-a315-7c750fcb2dcc">

**Comment by acesyde** [comment]
Et au même moment dans home assistant ?

**Comment by enamaryn** [comment]
> Et au même moment dans home assistant ?

Effectivement, c'est fait a 30 sec/1 minutes d'intervalle.

**Comment by acesyde** [comment]
Du coup on est bon non ?

**Comment by enamaryn** [comment]
Malheureusement non. J'étais à 100% sur le site Mylight alors que HA m'indique 54%

**Comment by acesyde** [comment]
Effectivement sur le site j'ai 100% Aussi alors que clairement je ne suis pas 100% autonome, je pense que que l'indicateur de leru côté n'est plus calculé correctement (après j'utilise jamais leur site)

![image](https://github.com/acesyde/hassio_mylight_integration/assets/958435/7dd7ea86-3bba-4680-93b3-c57e2517d6de)
